[package]
name = "kombi"
version = "0.1.0"
authors = ["Morgan Arnold <morgan.arnold@proton.me>"]
edition = "2021"
description = "An untyped lambda calculus written in Rust."
license = "Unlicense"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
pest = "2.7"
pest_derive = "2.7"
